language: go
go:
- 1.11.x
script:
- mkdir $GOPATH/src/2018_2_Stacktivity && cp ./* $GOPATH/src/2018_2_Stacktivity && cd $GOPATH/src/2018_2_Stacktivity
- chmod 777 "./make_bin.sh"
- ./make_bin.sh
- chmod 600 ./tp_blep
- ssh-keyscan -H $blep_ip >> ~/.ssh/known_hosts
- scp -i ./tp_blep -r bin *.Dockerfile docker-compose.yml grafana prometheus $blep_user@$blep_ip:/home/$blep_user/blep/back
- scp -i ./tp_blep ./nginx.conf $blep_user@$blep_ip:/home/$blep_user/backend.conf
- ssh -i ./tp_blep $blep_user@$blep_ip sudo mv /home/$blep_user/backend.conf /etc/nginx/conf.d/backend.conf
- ssh -i ./tp_blep $blep_user@$blep_ip sudo nginx -s reload
- ssh -i ./tp_blep $blep_user@$blep_ip cd /home/$blep_user/blep/back/ && sudo docker-compose
  build && sudo docker-compose restart
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_5afbc0103609_key -iv $encrypted_5afbc0103609_iv
  -in tp_blep.enc -out ./tp_blep -d
